services:
  keycloak:
    container_name: keycloak-pi-project
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
       - 9090:8080
    environment:
       KEYCLOAK_ADMIN: admin_farouk
       KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge